#pragma once
#include <QMap>
#include <QString>

inline QMap<QString,int> getZintSymbologies() {
    return {
        {"Code 128", 20},
        {"QR Code", 58},
        {"EAN-13", 4},
        {"UPC-A", 9},
        {"PDF417", 12},
        {"DataMatrix", 71},
        {"Aztec", 70},
        {"Code 39", 3},
        {"EAN-8", 1},
        {"UPC-E", 8},
        {"Code 93", 21},
        {"Code 11", 2},
        {"Interleaved 2 of 5", 5},
        {"Industrial 2 of 5", 6},
        {"Codabar", 7},
        {"Code 32", 22},
        {"Code 16K", 23},
        {"EAN-128", 25},
        {"UPC/EAN Extension", 26},
        {"EAN-14", 27},
        {"ITF-14", 28},
        {"Code 49", 29},
        {"Code 16K", 30},
        {"LOGMARS", 31},
        {"MaxiCode", 32},
        {"PDF417 Truncated", 33},
        {"MicroPDF417", 34},
        {"Micro QR Code", 35},
        {"DataBar", 36},
        {"DataBar Expanded", 37},
        {"DataBar Limited", 38},
        {"DataBar Stacked", 39},
        {"DataBar Stacked Omnidirectional", 40},
        {"DataBar Omnidirectional", 41},
        {"GS1 DataBar", 42},
        {"GS1 DataBar Expanded", 43},
        {"GS1 DataBar Limited", 44},
        {"GS1 DataBar Stacked", 45},
        {"GS1 DataBar Stacked Omnidirectional", 46},
        {"GS1 DataBar Omnidirectional", 47},
        {"Australia Post", 48},
        {"Channel Code", 49},
        {"Codablock F", 50},
        {"Code 2 of 5", 51},
        {"Code 2 of 5 IATA", 52},
        {"Code 2 of 5 Data Logic", 53},
        {"Code 2 of 5 Industrial", 54},
        {"Code 2 of 5 Matrix", 55},
        {"Code 39+", 56},
        {"Code 93+", 57},
        {"Code 128+", 59},
        {"EAN-13+", 60},
        {"UPC-A+", 61},
        {"EAN-8+", 62},
        {"UPC-E+", 63},
        {"EAN-128+", 64},
        {"ITF-14+", 65},
        {"Code 49+", 66},
        {"LOGMARS+", 67},
        {"MaxiCode+", 68},
        {"PDF417+", 69}
    };
}
